using System;
using System.Collections.Generic;

namespace OpenBurningSuite.Helpers;

public static class IconHelper
{
    private static readonly string AssemblyName = "OpenBurningSuite";

    public static string? GetUri(string key, int size = 50)
    {
        if (!AllKeys.TryGetValue(key, out var stem) || stem == null)
            return null;

        return $"avares://{AssemblyName}/Assets/Icons/{size}/{stem}-{size}.png";
    }

    public static readonly Dictionary<string, string> AllKeys = new()
    {
        ["Burn"] = "icons8-cd-3d",
        ["Disc"] = "icons8-cd-3d",
        ["Read"] = "icons8-cd-3d",
        ["Copy"] = "icons8-copy-2d",
        ["Dvd"] = "fluentui-dvd",
        ["Bd"] = "icons8-blu-ray-2d",
        ["DiscDvd"] = "fluentui-dvd",
        ["DiscEmpty"] = "icons8-empty-box",
        ["Audio"] = "icons8-music-3d",
        ["AudioDisc"] = "icons8-music-3d",
        ["MusicDisc"] = "icons8-music-3d",
        ["Video"] = "icons8-video-editing-3d",
        ["DvdVideo"] = "icons8-video-editing-3d",
        ["BdVideo"] = "icons8-video-editing-3d",
        ["Game"] = "icons8-game-controller",
        ["GamePatches"] = "icons8-game-controller",
        ["Settings"] = "icons8-settings-2d",
        ["Advanced"] = "icons8-settings-2d",
        ["Help"] = "icons8-info",
        ["Home"] = "icons8-home",
        ["Discover"] = "icons8-discover-2d",
        ["Build"] = "icons8-create",
        ["Verify"] = "fluentui-check-mark-button",
        ["Success"] = "fluentui-check-mark-button",
        ["Refresh"] = "icons8-refresh",
        ["Save"] = "icons8-save",
        ["Export"] = "icons8-export-2d",
        ["Clear"] = "icons8-erase",
        ["OpenFolder"] = "fluentui-open-file-folder",
        ["Add"] = "icons8-add",
        ["AddFile"] = "icons8-add-file",
        ["AddFolder"] = "icons8-add-folder",
        ["Remove"] = "icons8-remove",
        ["Delete"] = "icons8-delete-2d",
        ["Stop"] = "icons8-stop-2d",
        ["Pause"] = "icons8-pause-2d",
        ["Play"] = "icons8-play",
        ["Eject"] = "icons8-eject-2d",
        ["Load"] = "fluentui-open-file-folder",
        ["Speed"] = "icons8-speed-2d",
        ["MultiCopy"] = "icons8-duplicate-2d",
        ["Simulate"] = "icons8-test-passed",
        ["Wizard"] = "icons8-wizard-3d",
        ["Search"] = "icons8-search",
        ["Probe"] = "icons8-search",
        ["Analyze"] = "icons8-search",
        ["Lightbulb"] = "icons8-idea",
        ["Warning"] = "icons8-bang",
        ["Info"] = "icons8-info",
        ["ErrorSign"] = "icons8-error-sign",
        ["Lock"] = "icons8-lock-3d",
        ["Unlock"] = "fluentui-unlocked",
        ["Key"] = "fluentui-key",
        ["Folder"] = "icons8-folder",
        ["FolderTree"] = "icons8-folder-tree-2d",
        ["Data"] = "icons8-folder",
        ["Headphones"] = "icons8-headphones-2d",
        ["Playlist"] = "icons8-playlist-3d",
        ["Wav"] = "icons8-wav-2d",
        ["Volume"] = "fluentui-speaker-high-volume",
        ["Timeline"] = "icons8-timeline-3d",
        ["DataTransfer"] = "icons8-data-transfer",
        ["Clipboard"] = "fluentui-clipboard",
        ["Console"] = "icons8-console-3d",
        ["Dashboard"] = "icons8-dashboard-3d",
        ["GreenCircle"] = "fluentui-green-circle",
        ["OrangeCircle"] = "fluentui-orange-circle",
        ["FilmFrames"] = "fluentui-film-frames",
        ["NextTrack"] = "fluentui-next-track-button",
        ["MusicalNote"] = "fluentui-musical-note",
        ["Information"] = "fluentui-information",
        ["WarningSign"] = "fluentui-warning",
        ["OpticalDisk"] = "fluentui-optical-disk",
        ["ConsolePlaystation"] = "icons8-playstation-3d",
        ["ConsoleXbox"] = "icons8-xbox-2d",
        ["ConsoleNintendo"] = "icons8-nintendo-switch-2d",
        ["ConsoleSteam"] = "icons8-steam-deck-2d",
        ["ConsoleAtari"] = "icons8-atari-2d",
        ["ProgressIndicator"] = "icons8-progress-indicator-2d",
        ["Lightning"] = "icons8-lightning-bolt-3d",
        ["Loading"] = "icons8-loading-3d",
        ["Hourglass"] = "icons8-hourglass-2d",
        ["Clock"] = "icons8-clock",
        ["Globe"] = "icons8-globe-africa",
        ["FilmReel"] = "icons8-film-reel-3d",
        ["TapeDrive"] = "icons8-tape-drive-2d",
        ["Camera"] = "icons8-camera",
        ["VideoCard"] = "icons8-video-card",
        ["VideoCamera"] = "icons8-camera",
        ["Videotape"] = "icons8-tape-drive-2d",
        ["MovieCamera"] = "icons8-video-editing-3d",
        ["ThreeD"] = "icons8-video-editing-3d",
        ["Region"] = "icons8-globe-africa",
        ["Bootable"] = "icons8-idea",
        ["Reset"] = "icons8-refresh",
        ["Log"] = "icons8-console-3d",
        ["DiscInfo"] = "icons8-info",
        ["CopyWizard"] = "icons8-copy-2d",
        ["BlankWizard"] = "icons8-erase",
    };
}
