name: Build All

on:
  workflow_dispatch:
  push:
    tags: ['v*']

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    uses: ./.github/workflows/build-Windows.yml
    secrets: inherit

  build-linux:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  build-macos:
    uses: ./.github/workflows/build-macOS.yml
    secrets: inherit
